# Deployment Server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdci-gwf2
spec:
  selector:
    matchLabels:
      app: sdci-gwf2
  replicas: 1
  template:
    metadata:
      labels:
        app: sdci-gwf2
    spec:
      containers:
      - name: sdci-gwf2-container
        image: mathis05000/sdci-gwf:latest
        imagePullPolicy: Always
        env:
        - name: GW_NAME
          value: "gwf2"
        - name: DEVICE_NAME
          value: "dev2"
