# Deployment Server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdci-gwf3
spec:
  selector:
    matchLabels:
      app: sdci-gwf3
  replicas: 1
  template:
    metadata:
      labels:
        app: sdci-gwf3
    spec:
      containers:
      - name: sdci-gwf3-container
        image: mathis05000/sdci-gwf:latest
        imagePullPolicy: Always
        env:
        - name: GW_NAME
          value: "gwf3"
        - name: DEVICE_NAME
          value: "dev3"
