apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: metrics-access-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: metrics-access-sa
    namespace: default
roleRef:
  kind: Role
  name: metrics-access-role
  apiGroup: rbac.authorization.k8s.io
