# Service ClusterIP for Server
apiVersion: v1
kind: Service
metadata:
  name: sdci-gwf1
spec:
  selector:
    app: sdci-gwf1
  ports:
  - protocol: TCP
    name: http
    port: 8080
    targetPort: 8080
  type: ClusterIP
