# Service ClusterIP for Server
apiVersion: v1
kind: Service
metadata:
  name: sdci-gwi
spec:
  selector:
    app: sdci-gwi
  ports:
  - protocol: TCP
    name: http    
    port: 8080
    targetPort: 8080
  type: ClusterIP
