apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sdci-gwi
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sdci-gwi
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - pods:
      metric:
        name: istio_requests_per_second
      target:
        type: AverageValue
        averageValue: 0.1
    type: Pods
